### PR TITLE
Chore/remove duplicate keys

### PR DESCRIPTION
**Pull request by kevin-jackson**

### CODE REVIEW

**Comment by kevin-jackson** [comment]
@Ruxton

**Comment by psyren89** [comment]
I can't see anything other than whitespace being removed...

**Comment by sevenseacat** [comment]
Two lines of duplicated velocity calcs were removed also.

(not sure why I got notified about this PR, but hello)

**Comment by Ruxton** [comment]
@sevenseacat you're probably watching or favourited the project from moons ago.

**Comment by Ruxton** [comment]
Looks good @kevin-jackson ! 👍

**Pull request merged**
